# Generated by Django 4.2.10 on 2024-02-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='todoimage')),
            ],
        ),
    ]
